server:
  port: 8888
 
spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      default-filters:
      - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
         '[/**]':
           allowedOrigins: "*"
           allowedMethods: "*"
           allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
      - id: employeeservice
        uri: lb://employeeservice
        predicates:
        - Path=/employee/**
        filters:
          - AuthenticationFilter
        
      - id: managerservice
        uri: lb://managerservice
        predicates:
        - Path=/manager/**
        filters:
          - AuthenticationFilter
          
      - id: expenseservice
        uri: lb://expenseservice
        predicates:
        - Path=/expense/**
        filters:
          - AuthenticationFilter
          
      - id: identityservice
        uri: lb://identityservice
        predicates:
        - Path=/auth/**
        
  application:
    name: emsgateway


#eureka:
# client:
#  service-url:
#   defaultZone: http://localhost:8761/eureka
#           
#eureka:
#  client:
#    register-with-eureka: true
#    service-url:
#      default-zone : http://localhost:8761/eureka
#    instance:
#      preferIpAddress : true/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: localhost
      